
<section class="ftco-section">
<div class="container">
<div class="row justify-content-center">
<div class="col-md-6 text-center mb-5">
<h2 class="heading-section">BALLET PARKING</h2>
</div>
</div>
<div class="row justify-content-center">
<div class="col-md-7 col-lg-5">
<div class="login-wrap p-4 p-md-5">

<div class="icon d-flex align-items-center justify-content-center"> 
<i class="fa-solid fa-boxes-packing"></i>                                                                                                                                                                                                
</div>
<h3 class="text-center mb-4">Registrar Guardia</h3>
<form action="?seccion=5&dic=1" class="login-form" method="post">
<div class="form-group">
<input type="text" class="form-control rounded-left" placeholder="Usuario" name="reg_nombre" required>
</div>
<div class="form-group d-flex">
<input type="email" class="form-control rounded-left" placeholder="Correo" name="reg_correo" required>
</div>
<div class="form-group d-flex">
<input type="password" class="form-control rounded-left" placeholder="Contraseña" name="reg_contrasena" required>
</div>
<div class="form-group d-flex">
<input type="password" class="form-control rounded-left" placeholder="Confirmar Contraseña" name="con_contrasena" required>
</div>
<div class="form-group">
<!-- <button type="submit">Iniciar</button> -->
<input class="form-control btn btn-primary rounded submit px-3" type="submit" value="Registrar" name="enviar">
</div>
</form>
</div>
</div>
</div>
</div>
</section>