<div style="width: 100%; text-align: center;" id="registro" class="col-md-12">
    <h1>Sistema de recuperación de contraseña</h1>
    <form action="?seccion=8" method="post">

        <br><span>Correo:</span><br><input type="text" name="correo">
        <br><span>Nueva contraseña:</span><br><input type="text" name="contrasena">
        <br><span>Confirmar contraseña:</span><br><input type="text" name="conf_contra">

        <br><input class=" btn btn-primary" type="submit" value="ACTUALIZAR" name="enviar">

    </form>


</div>