
<section class="ftco-section">
<div class="container">
<div class="row justify-content-center">
<div class="col-md-6 text-center mb-5">
<h2 class="heading-section">BALLET PARKING</h2>
<h2 class="heading-section"><?php echo $_SESSION['nombre']; ?></h2>
<div class="col-md-12" style="margin-bottom: 20px;"><a class="btn btn-primary rounded submit px-3" href="cerrar_session.php?sep=2">Cerrar Session</a></div> 
</div>
</div>
<div class="row justify-content-center">
<div class="col-md-7 col-lg-5">
<div class="login-wrap p-4 p-md-5">

<div class="icon d-flex align-items-center justify-content-center"> 
<i class="fa-solid fa-boxes-packing"></i>                                                                                                                                                                                                
</div>
<h3 class="text-center mb-4">Registrar Bitacora</h3>
<form action="?seccion=11&vitacora=1" class="login-form" method="post">
<div class="form-group">
<input type="text" class="form-control rounded-left" placeholder="Cedula" name="reg_cedula" required>
</div>
<div class="form-group d-flex">
<input type="text" class="form-control rounded-left" placeholder="Matricula" name="reg_matricula" required>
</div>
<div class="form-group d-flex">
<input type="text" class="form-control rounded-left" placeholder="Nivel Gasolina" name="reg_gasolina" required>
</div>
<div class="form-group d-flex">
<input type="text" class="form-control rounded-left" placeholder="Kilometraje" name="reg_kilometraje" required>
</div>
<div class="form-group d-flex">
<input type="text" class="form-control rounded-left" placeholder="Notas" name="reg_notas" required>
</div>
<div class="form-group d-flex">
    <select style="width: 100%;" name="estado" id="estado">

        <option value="1">Ingreso</option>
        <option value="2">Salio</option>

    </select>
</div>
<div class="form-group">
<!-- <button type="submit">Iniciar</button> -->
<input class="form-control btn btn-primary rounded submit px-3" type="submit" value="Registrar" name="envia">
</div>
</form>
</div>
</div>
</div>
</div>
</section>