
<section class="ftco-section">
<div class="container">
<div class="row justify-content-center">
<div class="col-md-6 text-center mb-5">
<h2 class="heading-section">BALLET PARKING </h2> 

</div>
</div>
<div class="row justify-content-center">
<div class="col-md-7 col-lg-5">
<div class="login-wrap p-4 p-md-5">

<div class="icon d-flex align-items-center justify-content-center"> 
<i class="fa-solid fa-boxes-packing"></i>                                                                                                                                                                                                
</div>
<h3 class="text-center mb-4">Iniciar session</h3>
<form action="?seccion=10" class="login-form" method="post">
<div class="form-group">
<input type="text" class="form-control rounded-left" placeholder="Usuario" name="ini_correo" required>
</div>
<div class="form-group d-flex">
<input type="password" class="form-control rounded-left" placeholder="Contraseña" name="ini_contrasena" required>
</div>
<div class="form-group">
<!-- <button type="submit">Iniciar</button> -->
<input class="form-control btn btn-primary rounded submit px-3" type="submit" value="Iniciar" name="enviar">
</div>
<div class="form-group d-md-flex">
<div class="w-50">
<label class="checkbox-wrap checkbox-primary">Recordar
<input type="checkbox" checked>
<span class="checkmark"></span>
</label>
</div>
<div class="w-50 text-md-right">
<a href="?seccion=9">Recupera tu contraseña</a>
</div>
</div>
</form>
</div>
</div>
</div>
</div>
</section>
